### ISSUE TITLE
[Legitimate Site Blocked] storage.googleapis.com

### ISSUE THREAD

**Issue by Alemalu** [scamsniffer/scam-database#146]
https://storage.googleapis.com/glide-prod.appspot.com/uploads-v2/JpBjvjS3kz8o3HTS5VpD/pub/76amyQ3tP5WxQzjkFh64.png##211

**Comment by evgkrsk** [comment]
https://github.com/scamsniffer/scam-database/commit/f2c13849ffad9995827e0456b1db952edd38224f - here we go again.
