### ISSUE TITLE
[Legitimate Site Blocked] unitus.finance

### ISSUE THREAD

**Issue by Donald-Nobel** [scamsniffer/scam-database#152]
https://unitus.finance/##211

Unitus Finance, previous known as dForce lending (https://snapshot.org/#/dforcenet.eth/proposal/0x89c90f647cbd1df112636b5bdc4d8dfa3f5e5d177c70cad3f5dc13e146f46b20), is a well-known, reputative lending protocol, already launched on multiple chains, such as Ethereum, Arbitrum, Optimism, Base, Polygon, BNB Chain, etc.

DefiLlama has already launched the Unitus protocol(https://defillama.com/protocol/unitus#information) a long time ago. It has impressive TLV, a large user base, and vast interaction volumes everyday.

Please remove the “deceptive” label and mark domains related to Unitus.finance, including https://unitus.finance/ and https://app.unitus.finance/, as safe products. Thank you very much.

**Comment by stoltegg** [comment]
@Donald-Nobel Thanks for your report.

This cause it was flagged here:
https://github.com/MetaMask/eth-phishing-detect/issues/69770

Now we helped you unflag it:
https://github.com/MetaMask/eth-phishing-detect/commit/5d7d0cd2180a2453310650e34809caddf4b46a20
