### ISSUE TITLE
[Legitimate Site Blocked] pegasuscapital.xyz

### ISSUE THREAD

**Issue by Web3Securities** [scamsniffer/scam-database#184]
You previously added this site to the database and removed it from the list due to a mistake. I see that you have added this site back into your database. Or the site gives a warning even though you have not added it to the database. I think the problem can be solved if you add the site to the whitelist. There is no negative situation with this site. I request that it be reviewed again. https://pegasuscapital.xyz/

**Comment by stoltegg** [comment]
confirmed it's a phishing site.
