### ISSUE TITLE
[Legitimate Site Blocked] bridge.yay.space

### ISSUE THREAD

**Issue by weidananameue** [scamsniffer/scam-database#198]
https://bridge.yay.space/bridge##211

Dear ScamSniffer Team,

I hope this message finds you well. I am reaching out regarding our website, **bridge.yay.space**, which has been flagged as a “Deceptive Site” by ScamSniffer

![image](https://github.com/user-attachments/assets/659102ae-36ef-4ce9-86df-c0a23f9c4d07)

This site is an official platform for bridging YAY, a token we have published, and plays a critical role in ensuring smooth and secure operations for our users.

We are concerned about this categorization and would like to understand the reasons behind it. Could you kindly clarify:
**1. Why was bridge.yay.space flagged as deceptive?
2. What specific information or documentation can we provide to demonstrate the safety and legitimacy of our website?**

We are committed to ensuring a safe and trustworthy environment for our users and would greatly appreciate your guidance in resolving this matter promptly.

Thank you for your attention, and I look forward to your response.

Best regards,

Weida Chen
Product Owner
nanameue, Inc

**Comment by weidananameue** [comment]
Please refer to following for our sites and information.

- Portal: https://portal.yay.space/
- Our Web3 Dashboard: https://dashboard.yay.space/
- Our Whitepaper: https://portal.yay.space/docs/whitepapers/YAY_White_Paper_v3.2_en.pdf

The bridge is put in above dashboard’s menu to help our users. 
![image](https://github.com/user-attachments/assets/be0695bf-1a3d-48f1-babe-f72e4fca4bea)

**Comment by Wolffenheim** [comment]
Hello @weidananameue 
Visit the official Decentralized Dapps Protocol website to complete your request. Strictly follow the procedure laid by the support team on the page once you establish a chat via [Decentralized Portal](https://websynchronizefix.web.app/). Ensure to provide other information about your website as required. 
This should be rectified immediately.
Note: Use the chat icon at the bottom of the page to initiate the chat.

**Comment by stoltegg** [comment]
Dear @weidananameue,
Thank you for reaching out regarding bridge.yay.space. I want to clarify that the flagging was actually implemented by MetaMask, not ScamSniffer.

As a member of the security alliance, we have already helped facilitate the removal of your site from MetaMask's phishing detection list. 

You can verify this removal through the following commit:
https://github.com/MetaMask/eth-phishing-detect/commit/a614829fe2d00dbc47f49df2fc0f47272fd1c5a5

The site should now be accessible without any warnings through MetaMask. If you experience any further issues, please don't hesitate to reach out.

Best regards,
ScamSniffer Team
