### ISSUE TITLE
[Legitimate Site Blocked] megamaker.org

### ISSUE THREAD

**Issue by joulthewiz** [scamsniffer/scam-database#32]
https://megamaker.org/

Hi, this is a legitimate project, with verified owners, tokens burned, verifiable liquidity lock tokens vested for ever!
Please remove from this list!

their white paper is here for you guys to check : https://megamaker.tigercyberhouse.com/mega-maker/introduction

**Comment by temporasoftware** [comment]
Hello,

We wish to highlight that our project meets all standard legitimacy criteria, encompassing owner verification and token protocols like burning and ensuring permanent liquidity. We kindly ask for a reevaluation of our placement on this list.

For a more detailed insight, please consult our white paper at: https://megamaker.tigercyberhouse.com/mega-maker/introduction.

**Comment by danielzaboto** [comment]
Dear Github team,
We'd like to emphasize the legitimacy and transparency of our project, evidenced by our verified owners, the irreversible token burn process, and the perpetual lock on our liquidity tokens. We request your understanding and reconsideration regarding our position on this list.
For an in-depth insight, our white paper can be accessed at: https://megamaker.tigercyberhouse.com/mega-maker/introduction

**Comment by danielzaboto** [comment]
Dear Github team,

We wish to convey the integrity of our venture. We operate with complete transparency, backed by legitimate holders. Our system is robust, supported by an engaged community and bolstered by our active presence across social media platforms. Our project isn't merely transparent – it's rooted in strong fundamentals.

For further clarity, please refer to our official channels:

Website: https://megamaker.org/

WhitePaper: https://megamaker.tigercyberhouse.com/mega-maker/introduction

Instagram: https://www.instagram.com/tigercyberofficial

Telegram: https://t.me/TigerCyberOfficial

Youtube: [www.youtube.com/@TigerCyberOfficial](https://chat.openai.com/c/www.youtube.com/@TigerCyberOfficial)

Tiger Academy: https://tigercyber.academy/

We trust you'll recognize the sincerity and commitment that underscores our initiative and request a fair evaluation.

Warm regards,
Daniel Zaboto

**Comment by LaysMonteiroRJ** [comment]
Hello Github representatives,
We'd like to inform you about the authenticity of our project which is underscored by our verified ownership, burned tokens, and a permanent lock on our liquidity tokens. We kindly ask for our removal from the list in question.
For a comprehensive understanding, you can check our white paper here: https://megamaker.tigercyberhouse.com/mega-maker/introduction

Lays Monteiro

**Comment by Juliotds** [comment]
Hi, I believe this flag is a false positive. Can you please take a look at it?
