### ISSUE TITLE
[Legitimate Site Blocked] perp.dappos.com & perp.dappos.org

### ISSUE THREAD

**Issue by Jiangyj19** [scamsniffer/scam-database#33]
dear scamsniffer team, this is bree from dappos team, I‘m reporting this wrong issue:
perp.dappos.org
This product is co-launched with the perpetual team and has been officially backed and proved by the perpetual team.

Please kindly check this tweet from the perpetual official account

https://twitter.com/perpprotocol

And help remove perp.dappos.org from the block list and we have been replied at Github too.

Appreciate your kind help!!

**Comment by Jiangyj19** [comment]
https://dappos.gitbook.io/docs/infrastructure-design/security/external-audits

**Comment by Jiangyj19** [comment]
![image](https://github.com/scamsniffer/scam-database/assets/55271153/e3df899b-94ea-41b4-80cb-8429344f4f50)

**Comment by stoltegg** [comment]
@Jiangyj19 removed, it's was synced from third-party.
