### ISSUE TITLE
Cryptocurrency exchange phishing website

### ISSUE THREAD

**Issue by tuomihhhhs** [scamsniffer/scam-database#38]
Here are some phishing websites I collected
They have been around for a long time and there are many victims who have been scammed
So I request you to block these websites
I will list them below:

https://apy-eth.net
https://earn-eth.org/
https://urgentdt.com/
https://get-usdc.org
https://apy-eth.net
https://apyeth.su
https://get-usdc.org
https://ethapy.net
https://usdreward.com
https://apyether.org/
https://usd2023.com/
https://earn-eth.net/

**Comment by rainb3rry** [comment]
How did you found them out?
