### ISSUE TITLE
[Legitimate Site Blocked] beacons.ai

### ISSUE THREAD

**Issue by hkyksk** [scamsniffer/scam-database#6]
https://beacons.ai/mrHiko/#Connect

This is my personal site link. Not sure why it's blocked.

**Comment by lljxx1** [comment]
> https://beacons.ai/mrHiko/#Connect
> 
> This is my personal site link. Not sure why it's blocked.
sorry for that, there has a lot of phishing sites using the `beacons.ai` for redirecting recently
