### ISSUE TITLE
[Legitimate Site Blocked] game.defikingdoms.com

### ISSUE THREAD

**Issue by MrZipper7** [scamsniffer/scam-database#78]
Good morning,

I'd like to request removal of the `game.defikingdoms.com` domain from your blocklist. This is the primary URL for our dapp, which has been in active development since August 2021, and at the peak of the last bull market was one of the Top 100 coins with a market cap of over $1b.

You can verify this URL as listed on our main website at: https://defikingdoms.com, as well as on CoinMarketCap: https://coinmarketcap.com/currencies/defi-kingdoms/.

Thank you for your prompt attention! Please reach out if you have any questions or concerns.

**Comment by MrZipper7** [comment]
As an additional note, I will add that all of the _other_ DeFi Kingdoms related domains in your blocklist are indeed scams and should remain blocked. We appreciate the diligence of the ScamSniffer team in keeping people safe from these!

**Comment by stoltegg** [comment]
removed
