### ISSUE TITLE
[Legitimate Site Blocked] cloudflare-ipfs.com

### ISSUE THREAD

**Issue by saremeskandary** [scamsniffer/scam-database#97]
https://cloudflare-ipfs.com/ipfs/QmQt6HCahdCJtQNeBiXQiLWayF1Gegud27wzymSdFCmAWH/##211

**Comment by saremeskandary** [comment]
https://app.compound.finance/

**Comment by solanagavno** [comment]
> https://cloudflare-ipfs.com/ipfs/QmQt6HCahdCJtQNeBiXQiLWayF1Gegud27wzymSdFCmAWH/##211

drainer phishing link
